on: [workflow_dispatch]

jobs:
  approval:
    runs-on: ubuntu-latest
    environment:
      name: production-approval
    steps:
    - name: waiting
      run: |
        echo "Waiting for approval"
    
  release-1:
    needs: approval
    runs-on: ubuntu-latest
    environment:
        name: production
    steps:
    - name: deploying
      run: |
        echo "Deploying parallel #1..."
    
  release-2:
    needs: approval
    runs-on: ubuntu-latest
    environment:
        name: production
    steps:
    - name: deploying
      run: |
        echo "Deploying parallel #2..."
    
  release-3:
    needs: approval
    runs-on: ubuntu-latest
    environment:
        name: production
    steps:
    - name: deploying
      run: |
        echo "Deploying parallel #3..."
