on: [workflow_dispatch]

name: Deploy in Parallel Upon Approval

jobs:
  approval:
    runs-on: ubuntu-latest
    environment:
      name: production-approval
    steps:
    - name: waiting
      run: |
        echo "Waiting for approval"
    
  release-1:
    needs: approval
    runs-on: ubuntu-latest
    environment:
        name: production
    steps:
    - name: deploying
      env:
        MY_SECRET: ${{ secrets.MY_ENV_SECRET }}
      run: |
        echo "Deploying parallel #1..."
        sleep $[ ( $RANDOM % 10 )  + 1 ]s
        echo $MY_SECRET
        echo "Deploying parallel #1 complete!"
    
  release-2:
    needs: approval
    runs-on: ubuntu-latest
    environment:
        name: production
    steps:
    - name: deploying
      env:
        MY_SECRET: ${{ secrets.MY_ENV_SECRET }}
      run: |
        echo "Deploying parallel #2..."
        sleep $[ ( $RANDOM % 10 )  + 1 ]s
        echo $MY_SECRET
        echo "Deploying parallel #2 complete!"
    
  release-3:
    needs: approval
    runs-on: ubuntu-latest
    environment:
        name: production
    steps:
    - name: deploying
      env:
        MY_SECRET: ${{ secrets.MY_ENV_SECRET }}
      run: |
        echo "Deploying parallel #3..."
        sleep $[ ( $RANDOM % 10 )  + 1 ]s
        echo $MY_SECRET
        echo "Deploying parallel #3 complete!"
