name: GitHub Actions PS Remoting Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: PsRemoting
        shell: pwsh
        run: |
          # Set-Item WSMan:\localhost\Client\TrustedHosts -Value '*'
          # winrm set winrm/config/client '@{TrustedHosts="*"}'
          $secpasswd = ConvertTo-SecureString ${{ secrets.VM_PASSWORD }} -AsPlainText -Force
          write-output "${{ env.VM_USERNAME }} is the current username"
          $mycreds = New-Object System.Management.Automation.PSCredential ("${{ env.VM_USERNAME }}", $secpasswd)
          $session = New-PSSession -ComputerName cw-sql-test.sullivanenterprises.org -Credential $mycreds
          Invoke-Command -Session $session -ScriptBlock { invoke-sqlcmd -query "SELECT TOP (1000) [optname],[value],[major_version],[minor_version],[revision],[install_failures] FROM [master].[dbo].[MSreplication_options]" -ServerInstance 'SQLVM001' }
          Remove-PSSession -Session $session
      - run: echo "🍏 This job's status is ${{ job.status }}."
