on: [workflow_dispatch]

name: SQL Deploy Demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Retrieve secret from KV
      uses: azure/cli@v1
      with:
        inlineScript: |
          secretValue=$(az keyvault secret show --name "dbconnstr" --vault-name "gh-actions-20231204-kv" --query "value")
          echo "CONN_STR="$secretValue >> $GITHUB_ENV

    - uses: azure/sql-action@v2.2
      with:
        connection-string: $CONN_STR
        path: './Database.dacpac'
        action: 'publish'
        arguments: 'select getdate()'
 

# jobs:
#   approval:
#     runs-on: ubuntu-latest
#     environment:
#       name: production-approval
#     steps:
#     - name: waiting
#       run: |
#         echo "Waiting for approval"
    
#   release-1:
#     needs: approval
#     runs-on: ubuntu-latest
#     environment:
#         name: production
#     steps:
#     - name: deploying
#       env:
#         MY_SECRET: ${{ secrets.MY_ENV_SECRET }}
#       run: |
#         echo "Deploying parallel #1..."
#         sleep $[ ( $RANDOM % 10 )  + 1 ]s
#         echo $MY_SECRET
#         echo "Deploying parallel #1 complete!"
    
#   release-2:
#     needs: approval
#     runs-on: ubuntu-latest
#     environment:
#         name: production
#     steps:
#     - name: deploying
#       env:
#         MY_SECRET: ${{ secrets.MY_ENV_SECRET }}
#       run: |
#         echo "Deploying parallel #2..."
#         sleep $[ ( $RANDOM % 10 )  + 1 ]s
#         echo $MY_SECRET
#         echo "Deploying parallel #2 complete!"
    
#   release-3:
#     needs: approval
#     runs-on: ubuntu-latest
#     environment:
#         name: production
#     steps:
#     - name: deploying
#       env:
#         MY_SECRET: ${{ secrets.MY_ENV_SECRET }}
#       run: |
#         echo "Deploying parallel #3..."
#         sleep $[ ( $RANDOM % 10 )  + 1 ]s
#         echo $MY_SECRET
#         echo "Deploying parallel #3 complete!"
