on: [workflow_dispatch]

name: SQL Deploy Demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - id: get-kv-conn-str
      name: Retrieve secret from KV
      uses: azure/cli@v1
      with:
        inlineScript: |
          kv_secret=$(az keyvault secret show --name "dbconnstr" --vault-name "gh-actions-20231204-kv" --query value -o tsv)
          echo "::add-mask::$kv_secret"
          echo "ConnectionString=$kv_secret" >> "$GITHUB_OUTPUT"

    - uses: azure/sql-action@v2.2
      with:
        connection-string: ${{ steps.get-kv-conn-str.outputs.ConnectionString}}
        path: './sqlscripts/CREATETABLE.sql'
